repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.9.1
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
          - --template-files=README.md.gotmpl
