suite: test deployment

templates:
  - deployment.yaml

release:
  name: actualbudget
  namespace: actualbudget

chart:
  version: 1.0.0
  appVersion: 1.0.0

tests:
  - it: should be custom service account when we do not create it
    set:
      serviceAccount.create: false
      serviceAccount.name: customsa
    asserts:
      - equal:
          path: spec.template.spec.serviceAccountName
          value: customsa

  - it: should show actual post environment variable
    set:
      service.port: 1234
    asserts:
      - contains:
          path: spec.template.spec.containers[?(@.name == "actualbudget")].env
          content:
            name: ACTUAL_PORT
            value: "1234"

  - it: should show actual server files environment variable
    set:
      files.server: "/somewhere/server"
    asserts:
      - contains:
          path: spec.template.spec.containers[?(@.name == "actualbudget")].env
          content:
            name: ACTUAL_SERVER_FILES
            value: "/somewhere/server"

  - it: should show actual user files environment variable
    set:
      files.user: "/somewhere/user"
    asserts:
      - contains:
          path: spec.template.spec.containers[?(@.name == "actualbudget")].env
          content:
            name: ACTUAL_USER_FILES
            value: "/somewhere/user"
