suite: test service

templates:
  - service.yaml

tests:
  - it: should use different port number when we change it
    set:
      service.port: 80
    asserts:
      - contains:
          path: spec.ports
          content:
            port: 80
          any: true
