name: 🚀 Chart Request
description: Suggest a new Helm chart for an open-source project.
title: "[Chart Request]: "
labels: ["new chart request", "enhancement"]
assignees: ["contributors"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the Community Charts organization! We appreciate you suggesting new projects that could benefit from community-maintained Helm charts.

        Before submitting, please make sure you've:
        - Searched [existing issues](https://github.com/community-charts/helm-charts/issues) to ensure this request hasn't already been made.
        - Read our [contribution guidelines](https://github.com/community-charts/helm-charts/blob/main/CONTRIBUTING.md) (please create this file if it doesn't exist, or update the link) to understand our process.

  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: What is the name of the open-source project you're suggesting a chart for?
      placeholder: e.g., "My Awesome Project"
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Provide a brief description of the project and its primary purpose.
      placeholder: e.g., "My Awesome Project is a data processing tool that helps users clean and transform large datasets efficiently."
    validations:
      required: true

  - type: input
    id: project-github-link
    attributes:
      label: Project GitHub / Website Link
      description: Link to the project's official GitHub repository (or main website if no GitHub repo).
      placeholder: e.g., "https://github.com/my-org/my-awesome-project" or "https://myawesomeproject.org"
    validations:
      required: true

  - type: dropdown
    id: official-chart-status
    attributes:
      label: Does this project currently have any official Helm charts?
      options:
        - "No (no official chart exists)"
        - "Yes, but it's unmaintained/deprecated"
        - "Yes, but it's incomplete/lacks features"
        - "Unsure"
      default: 0 # Corresponds to the first option "No"
    validations:
      required: true

  - type: textarea
    id: chart-justification
    attributes:
      label: Justification for a Community Chart
      description: Please explain why you believe this project needs a community-maintained Helm chart, given its current official chart status (if any).
      placeholder: e.g., "The official chart was abandoned after the company was acquired, or 'There's never been an official chart for this project.'"
    validations:
      required: true

  - type: textarea
    id: chart-requirements
    attributes:
      label: Desired Chart Features/Configurations
      description: Are there any specific features or configurations you would expect the Helm chart to support?
      placeholder: e.g., "PostgreSQL database integration, Ingress support, Persistent Volume Claims, horizontal scaling, custom resource definitions (CRDs) if applicable, etc."
    validations:
      required: false

  - type: textarea
    id: chart-dependencies
    attributes:
      label: Known Project Dependencies
      description: Are there any known dependencies for this project that would also need to be managed or integrated by the Helm chart (e.g., database, message queue, other services)?
      placeholder: e.g., "Requires a PostgreSQL database," "Uses Redis for caching," "Needs an external S3 bucket."
    validations:
      required: false

  - type: checkboxes
    id: willingness-to-contribute
    attributes:
      label: Willingness to Contribute
      description: Are you interested in contributing to the development of this new Helm chart?
      options:
        - label: Yes, I'd like to help by writing chart definitions, testing, or reviewing.
        - label: Yes, I'd be happy to provide feedback and test the chart once it's available.
        - label: No, I'm just requesting it.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant for creating this chart? (e.g., "This project is commonly deployed alongside X," "It uses a specific configuration pattern.")
    validations:
      required: false