suite: test deployment

templates:
  - deployment.yaml

tests:
  - it: should be custom service account when we do not create it
    set:
      serviceAccount.create: false
      serviceAccount.name: customsa
    asserts:
      - equal:
          path: spec.template.spec.serviceAccountName
          value: customsa

  - it: should show actual post environment variable
    set:
      service.port: 1234
    asserts:
      - equal:
          path: spec.template.spec.containers[0].env[0].name
          value: PYPISERVER_PORT
      - equal:
          path: spec.template.spec.containers[0].env[0].value
          value: "1234"

  - it: should pass PyPiServer arguments
    set:
      podArgs:
        - run
        - --version
    asserts:
      - equal:
          path: spec.template.spec.containers[0].args[0]
          value: run
      - equal:
          path: spec.template.spec.containers[0].args[1]
          value: --version
