suite: test service

templates:
  - service.yaml

tests:
  - it: should use different port number when we change it
    set:
      service.port: 80
    asserts:
      - equal:
          path: spec.ports[0].port
          value: 80
