suite: test pdb

templates:
  - pdb.yaml

tests:
  - it: should create pdb when all nodes flag disabled
    set:
      replica.allNodes: false
    asserts:
      - hasDocuments:
          count: 1

  - it: should not create pdb when all nodes flag enabled
    set:
      replica.allNodes: true
    asserts:
      - hasDocuments:
          count: 0
