suite: test ingress

templates:
  - ingress.yaml

tests:
  - it: should be empty when ingress is not enabled
    asserts:
      - hasDocuments:
          count: 0

  - it: should match snapshot of default values
    set:
      ingress.enabled: true
      ingress.className: nginx-test
    release:
      name: outline
      namespace: outline
    chart:
      version: 1.0.0
      appVersion: 1.0.0
    asserts:
      - matchSnapshot: { }
