apiVersion: v2
name: drone
description: A Helm chart for Drone Server and Drone Kubernetes Runner
icon: https://raw.githubusercontent.com/drone/brand/master/logos/png/dark/drone-logo-png-dark-128.png

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.26.0"

kubeVersion: ">=1.13.0-0"

home: https://www.drone.io

maintainers:
  - name: burakince
    email: burak.ince@linux.org.tr
    url: https://www.burakince.com

sources:
  - https://github.com/community-charts/helm-charts
  - https://github.com/drone

keywords:
  - kubernetes
  - drone
  - drone.io
  - droneci
  - drone-ci
  - CI
  - CD
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - code-pipeline

annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/community-charts/helm-charts
    - name: Chart Usage Page
      url: https://community-charts.github.io/docs/charts/drone/usage
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - kind: changed
      description: Update drone/drone image version to 2.26.0
      links:
        - name: Upstream Project
          url: https://hub.docker.com/r/drone/drone
  artifacthub.io/images: |
    - name: drone
      image: drone/drone:2.26.0
      platforms:
        - linux/amd64
        - linux/arm64
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: burakince
      email: burak.ince@linux.org.tr
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/screenshots: |
    - title: Build List
      url: https://raw.githubusercontent.com/drone/brand/master/screenshots/screenshot_build_list.png
    - title: Build Running
      url: https://raw.githubusercontent.com/drone/brand/master/screenshots/screenshot_build_running.png
    - title: Build Success
      url: https://raw.githubusercontent.com/drone/brand/master/screenshots/screenshot_build_success.png
    - title: Build Failure
      url: https://raw.githubusercontent.com/drone/brand/master/screenshots/screenshot_build_failure.png
  artifacthub.io/signKey: |
    fingerprint: 939B1A0ED8AAA8E722ACCDB3B6A012EE8A76426A
    url: https://keybase.io/communitycharts/pgp_keys.asc

dependencies: []
