{{- if and .Values.kubeRunner.enabled .Values.kubeRunner.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drone.runnerServiceAccountName" . }}
  labels:
    {{- include "drone.runnerLabels" . | nindent 4 }}
  {{- with .Values.kubeRunner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.kubeRunner.serviceAccount.automount }}
{{- end }}
