apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "outline.fullname" . }}-entrypoint
  labels:
    app: {{ include "outline.name" . }}
    chart: {{ include "outline.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ (.Files.Glob "files/entrypoint.sh").AsConfig | nindent 2 }}
