apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    {{- include "cloudflared.selectorLabels" . | nindent 4 }}
